version: '3.8'

services:
  squid:
    image: ubuntu/squid:latest
    container_name: squid-proxy
    restart: unless-stopped
    ports:
      - "3128:3128"
    volumes:
      - ./squid.conf:/etc/squid/squid.conf:ro
      - ./logs:/var/log/squid
      - ./cache:/var/spool/squid
    environment:
      - TZ=UTC
    networks:
      - squid-network
    healthcheck:
      test: ["CMD", "squidclient", "-h", "localhost", "-p", "3128", "mgr:info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  squid-network:
    driver: bridge