#!/usr/bin/env bash
# =============================================================================
# generate-inventory.sh — build the Ansible inventory from `vagrant ssh-config`.
# No SSH port or key path is ever hardcoded; everything comes from Vagrant.
# =============================================================================
set -Eeuo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${SCRIPT_DIR}/lib/common.sh"
setup_err_trap

INV_DIR="${PROJECT_DIR}/inventory/generated"
INV_FILE="${INV_DIR}/hosts.ini"
mkdir -p "$INV_DIR"

log_step "Generating Ansible inventory from vagrant ssh-config"

cfg="$(cd "$PROJECT_DIR" && vagrant ssh-config 2>/dev/null)" \
  || die "vagrant ssh-config failed (is the VM up?). Run: vagrant up"

get() { awk -v k="$1" 'tolower($1)==tolower(k){print $2; exit}' <<<"$cfg"; }

host="$(get HostName)"
port="$(get Port)"
user="$(get User)"
key="$(get IdentityFile)"

[[ -n "$host" && -n "$port" && -n "$user" && -n "$key" ]] \
  || die "incomplete ssh-config (host='$host' port='$port' user='$user' key='$key')"

# IdentityFile may be quoted by Vagrant; strip quotes.
key="${key%\"}"; key="${key#\"}"

umask 077
cat > "$INV_FILE" <<EOF
# Auto-generated by generate-inventory.sh from \`vagrant ssh-config\`.
# DO NOT EDIT or COMMIT — transient SSH host/port/key. (gitignored)
[awx_vm]
awx_guest ansible_host=${host} ansible_port=${port} ansible_user=${user} ansible_ssh_private_key_file=${key}

[awx_vm:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=20'
EOF
chmod 0600 "$INV_FILE"

log_ok "Inventory written: ${INV_FILE} (host=${host} port=${port} user=${user})"
